config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  resources :books
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  mount Notifications::Engine => "/notifications"

  get '/search' => 'pages#search', :as => 'search_page'
  
  get 'pages/quiz'
  get 'pages/about'
  get 'pages/gallery'
  get 'pages/help'
  get 'pages/payment'
  get 'pages/covid'
  resources :profiles
  get 'certificate/index'
  get 'requests/update'
  resources :credits
  authenticate :user, lambda { |u| u.user_role == "admin" } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
  resources :replies
  resources :homepage
  resources :favorites, only: [:index, :destroy, :create, :show]
  resources :completes, only: [:create, :destroy]

  get 'comments/create'
  get 'course/assesment'
  get 'welcome/index'
  get 'exam/assesment'
  get 'users/index'
  get 'report', to: 'favorites#report', as: 'report'
  get 'all_favorite', to: 'favorites#all_favorite', as: 'all_favorite'
  get 'instructor', to: 'users#instructor', as: 'instructor'
  get 'professional', to: 'users#professional', as: 'professional'
  get 'search', to: 'users#search', as: :search
  get 'quiz', to: 'users#quiz', as: 'quiz'


  devise_for :users, controllers: {
    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, :only =>[:show, :index]
resources :courses do
  collection do
    get :all_course
  end
  resources :comments do
    resources :replies
  end
end


  root to: "homepage#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :course, optional: true
  mount_uploader :video, VideoUploader
  mount_uploader :upload_file, UploadFileUploader
  validates :discription, :name, presence: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_params
      params.require(:credit).permit(:name, :upload_file, :user_id, :course_id, :video, :discription)
    end
    def uploadFile
      credit = Credit.save(params[:upload])
      render :text => "File has been uploaded successfully"
    end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.erb
<section class="gray pt-0">
				<div class="container-fluid">
										
					<div class="row">
					
						<div class="col-lg-3 col-md-3 p-0">
							<div class="dashboard-navbar">								
                <div class="d-user-avater">                
                <% if user_signed_in? %>
                <% if current_user.profile == nil %>
                  <p><%= image_tag 'default.png', class:"img-fluid avater" %></p>
                  <%= link_to 'upload a profile picture', new_profile_path, class: "btn btn-success " %>
                <% else %>
                <% if current_user.profile.image? %>
                  <p><%= image_tag current_user.profile.image.url, class:"img-fluid avater" %></p>
                  <%= link_to 'view Profile picture', profiles_path, class:"pull-right", style:"margin-left:70em; margin-top: -10px;" %></li>
                <% end %>
                <% end %>
              <% end %>
              <h4><%= current_user.names %> <%= current_user.last_name %></h4>
              <span class="text-secondary"><%= current_user.working_place %></span>
            </div>
								
								<div class="d-navigation">
									<ul id="side-menu">
										<li ><a href="settings.html"><i class="ti-user"></i>My Profile</a></li>
										<li><a href="password.html"><i class="ti-settings"></i>Change my Password</a></li>
										<li class="dropdown active">
											<a href="#"><i class="ti-layers"></i>My Courses<span class="ti-angle-left"></span></a>
											<ul class="nav nav-second-level show">
												<li><a href="course-settings.html">0038 Primary Eye Healthcare Modules</a></li>
												<li class="active"><a href="course-settings.html">0038 Primary Eye Healthcare Modules</a></li>
												<li><a href="course-settings.html">0038 Primary Eye Healthcare Modules</a></li>
												<li><a href="course-settings.html">0038 Primary Eye Healthcare Modules</a></li>
											</ul>
										</li>
										<li><a href="add-new-course.html"><i class="ti-plus"></i>Add new Course</a></li>
										<li><a href="add-new-book.html"><i class="ti-plus"></i>Add new Book</a></li>
										<li><a href="#"><i class="ti-power-off"></i>Log Out</a></li>
									</ul>
								</div>

							</div>
						</div>
						<div class="col-lg-9 col-md-9 col-sm-12">
							<!-- Row -->
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 pt-4 pb-4">
									<nav aria-label="breadcrumb">
										<ol class="breadcrumb">
											<li class="breadcrumb-item"><a href="#">Home</a></li>
											<li class="breadcrumb-item"><a href="#">My Dashboard</a></li>
											<li class="breadcrumb-item"><a href="#">My Courses</a></li>
											<li class="breadcrumb-item"><a href="#">Modules</a></li>
											<li class="breadcrumb-item active" aria-current="page">Add new Module</li>
										</ol>
									</nav>
								</div>
							</div>
							<!-- /Row -->
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
									<div class="prc_wrap">
                      <div class="prc_wrap-body">
                      <%= form_with(model: credit, local: true) do |form| %>
                        <% if credit.errors.any? %>
                          <div id="error_explanation">
                            <h2><%= pluralize(credit.errors.count, "error") %> prohibited this credit from being saved:</h2>
                      
                            <ul>
                              <% credit.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                            </ul>
                          </div>
                        <% end %>
                       

												<div class="row">
													<div class="col-lg-6 col-md-12">
														<div class="form-group">
															<label>Module Title</label>
                              <%= form.text_field :name, :required => true, class:"form-control simple" %>
														</div>
													</div>
													<div class="col-lg-6 col-md-12">
														<div class="form-group">
															<label>Upload file</label>
                              <%= form.file_field :upload_file, class:"form-control simple disabled" %>
														</div>
													</div>
													<div class="col-lg-12 col-md-6">
														<div class="form-group">
															<label>Description</label>
                              <%= form.cktext_area :discription, :ckeditor => {:toolbar => 'img', :customConfig => asset_path('ckeditor/config.js')} %>
														</div>
                          </div>
                          <div class="col-lg-12 col-md-6">
                          <div class="form-group">
                            <%= form.hidden_field :course_id, :value => params[:course_id] %>
                          </div>
                        </div>
												</div>
												<div class="form-group">
                        <%= form.submit class:"btn btn-success"%>
												</div>
											</div>

										</div>

								</div>
							</div>
					
					</div>
					
					</div>
				</div>
      </section>
      <% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form', credit: @credit %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>courses Module</h1>
<hr class="hr">

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Discription</th>
      <th>Upload file</th>
      <th>Course Name</th>
      <th>Video</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.name %></td>
        <td><%= credit.discription.html_safe %></td>
        <td><%= link_to "Download", credit.upload_file_url %></td>
        <td><%= credit.course.title %></td>
        <td><video controls width="300" src="<%= credit.video %>"></video></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Add Module', new_credit_path %>

app/views/credits/new.html.erb
<h1>New Module</h1>
<hr class="hr"

<%= render 'form', credit: @credit %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<div class="custom-breadcrumns border-bottom">
      <div class="container">
        <%= link_to "Home", homepage_index_path,:"data-no-turbolink"=>true,method:"get" %>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <%= link_to "Courses", courses_path,:"data-no-turbolink"=>true,method:"get" %>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
        <span class="current">Module</span>
      </div>
    </div>

<div class="card" style='width:70%;margin:auto'>
<!-- Card content -->
<div class="card-body">
<div class="site-section">

                <div class="col-lg-12 ml-auto align-self-center">
                        <h2 class="section-title-underline mb-5">
                            <span><%= @credit.name %></span>
                        </h2>

                        <p><%= @credit.discription.html_safe %></p>





                    </div>

    </div>



</div>
</div><br><br>